sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

script: bin/kahlan --coverage=3 --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '5.6' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    secure: pSNrc/EfF+cwXbRFS4PjCNt1bWhaa2wi6Ta6yHvFA5b+17aj9Nt6lQS10su8za/QxcLTWSZYQCeX1dawDxVdJLIB+ZL2+chTvjprMoqGpRigKQGMPYThEwpZmhpDvSXtZBq9RBJrTXmm/FcDWtME/cIro1fPWqPmgMrWWyc9N2MZSumeM/2pBUj4r6lMrVcYXTwbYuHcbvXWisCnpLSE+q7jHxr7eyQjrrJijU2yc0ciUqza6xFYCKi1Dr1ltZpOAv0ZHtqn0vmmhherPQCcUSW07d8AI9D2gHUFRidETo6imESHvZpCCU9WNjqS5aNVXgKLYBqr+n+fHDPswcV4s9pMnFd/SlRGyTS1aqC2ysYBD/3IETQAbHnnz13IJIhespV4uk8m/6n1eYUprVgP49N6Q4XBBHEu+u4dSpJf28FN2EYN6dAQKR04J4v34xaHDBtICHbevmniAq5JitZWi7icHqxcRTIYk+Q+AxBQ+VFV02dCpapW9V7MoMYvyZfjWXiRTCGnZkgNiYErAPzY8Lonkn4izlYZSAWfuxiZEQfSVdZMkPlLv6DLaYOwkKPzVupKQpazMfAbOMH2oZ1noI96b6P/50/4XcoHhhDW2ltxwewsHUkoKY9Nkx/uTf2ou0aL/O7WQDv9xAUqwF6slDix2qicbTyv2GPsi+mMtyc=
